server:
  port: 8080
  tomcat:
    threads:
      max: 200                # 생성할 수 있는 thread의 총 개수
      min-spare: 20           # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8192     # 수립가능한 connection의 총 개수
    accept-count: 100         # 작업큐의 사이즈
    connection-timeout: 20000 # timeout 판단 기준 시간, default: 20초
  shutdown: graceful

spring:
  application:
    name: barogo
  datasource:
    url: jdbc:h2:mem:notice;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  # dev
    properties:
      hibernate:
        format_sql: true
        show_sql: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  issuer: barogo-delivery
  secret: barogo-deliverybarogo-deliverybarogo-delivery
  access-token-validity-sec: 3600
  refresh-token-validity-sec: 1209600

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha           # 엔드포인트를 알파벳 순으로 정렬
    tagsSorter: alpha                 # 태그를 알파벳 순으로 정렬
    display-request-duration: true    # 요청 소요 시간 표시
    display-operation-id: false        # Operation ID 표시
    defaultModelsExpandDepth: 1       # Models 섹션의 기본 펼침 깊이 설정
    doc-expansion: list               # 전체 API 설명이 기본적으로 접힘
    disable-swagger-default-url: false # 기본 URL 비활성화
    persistAuthorization: true       # 인증 정보 저장 여부
    validator-url:                    # 스키마 유효성 검사 URL
    filter: true                      # 필터 사용 여부
    deep-linking: false              # 딥링킹 사용 여부